Move ClusterAssociated to the clusters module
rhevm-qe-automation/ovirtlib4 pull request #15
Opened 2022-03-09 09:13 UTC by roniezr

This patch fixes an error due to import loop

2022-03-09 12:24 UTC, kobihk approved these changes

2022-03-10 16:49 UTC, MosheSheena requested changes
To me it feels like ClusterAssociated doesn't belong in the clusters module.
When I think about it, to me it sounds reasonable that the clusters module contains all the information and actions you can perform with clusters, yet it doesn't feel right putting this class in that module.
Please help me understand why you found this to be the right move to make here.
I'm actually more in favor of creating some higher level module where classes like ClusterAssociated could be populated.

2022-03-15 12:59 UTC, roniezr commented
> To me it feels like ClusterAssociated doesn't belong in the clusters module. When I think about it, to me it sounds reasonable that the clusters module contains all the information and actions you can perform with clusters, yet it doesn't feel right putting this class in that module. Please help me understand why you found this to be the right move to make here. I'm actually more in favor of creating some higher level module where classes like ClusterAssociated could be populated.

The question is this work for? is this eliminates the import problem?
I don't think we need to create new module for that, it belongs to Clusters it returns a Cluster class that sit in this module
so why opening a new module and import Clusters into it?

2022-03-15 13:45 UTC, MosheSheena approved these changes
I believe this design is faulty, and should be carefully reconsidered.
Regardless of that I will point out that this current commit has resolved the circular dependency issue.

2022-03-16 08:58 UTC, merged