Add VM snapshots
rhevm-qe-automation/ovirtlib4 pull request #16
Opened 2022-11-27 13:41 UTC by roniezr

2022-11-27 13:47 UTC, kobihk requested changes

2022-11-27 13:47 UTC, kobihk commented on ovirtlib4/vms.py
> +    def snapshots(self):
maybe it will be better to keep the same obj name
```suggestion
    def vm_snapshots(self):
```

2022-11-29 10:53 UTC, roniezr commented on ovirtlib4/vms.py
> +    def snapshots(self):
It is a class method that belong to a VM class, so it is not acceptable to duplicate the class name into the method

e.g:
the class is a VM instance, so you will have 
vm = VM()
vm.vm_snapshots()
vm.vm_disks()
vm.vm_nics()

instead of:
vm.snapshots()
vm.disks()
vm.nics()

2022-11-29 10:54 UTC, kobihk commented on ovirtlib4/vms.py
> +    def snapshots(self):
OK, Thanks!!

2022-11-29 10:54 UTC, kobihk approved these changes

2022-11-29 12:16 UTC, merged